name: Get content from most recent md file in folder

on:
    push:
        branches:
        - 'main'
        paths: 
        - 'notes/*'

jobs:
  get-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get contents of the latest MD file
        id: md-file
        uses: JumboWumbus/get-md-file-contents@master
        with:
          gh_token: ${{ github.token }}
          articles_folder: notes
          
      - name: Take content and tweet it to twitter
        uses: dart-actions/tweet@v1.0.0
        with:
          text: "Test generating a tweet from MD file in github actions: ${{steps.md-file.outputs.content}}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
