name: Send a Tweet

on:
    [push]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: dart-actions/tweet@v1.0.0
        with:
          text: "Hello, World! Testing tweeting via github actions to do spicy stuff."
          bearer-token: ${{ secrets.TWITTER_BEARER_TOKEN }}
