name: Test

on:
  push:
    branches: ["main"]
jobs:
  test-tweet:
    name: Test Tweet
    runs-on: ubuntu-latest
    
    steps:
    - name: Tweet
      uses: snow-actions/tweet@v1.4.0
      with:
        status: |
          Testing sending a tweet via github actions to see if I can do something fancy!
    env:
      CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET_KEY }}
      ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
